import type { Product, StoreProfile, ChatThread, Comment } from "@/types/backend"

export const mockProducts: Product[] = [
  {
    id: "product_1",
    name: "Premium Gold Watch",
    description: "Luxury timepiece with 18k gold plating and Swiss movement. Perfect for special occasions and daily elegance.",
    price: 2500000,
    monthlyPrice: 0,
    likeCount: 24,
    commentCount: 5,
    saveCount: 12,
    storeId: "store_1",
    tier: "goldenRegular",
    media: {
      mainImage: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=512&h=512&fit=crop",
      imageCarousel: [
        "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=512&h=512&fit=crop",
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=512&h=512&fit=crop",
      ],
      is3DModel: false,
    },
  },
  {
    id: "product_2",
    name: "Designer Leather Bag",
    description: "Handcrafted Italian leather bag with gold hardware. Spacious interior with multiple compartments.",
    price: 1800000,
    monthlyPrice: 0,
    likeCount: 18,
    commentCount: 3,
    saveCount: 8,
    storeId: "store_1",
    tier: "goldenRegular",
    media: {
      mainImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=512&h=512&fit=crop",
      imageCarousel: [
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=512&h=512&fit=crop",
      ],
      is3DModel: false,
    },
  },
  {
    id: "product_3",
    name: "Crystal Chandelier",
    description: "Elegant crystal chandelier with gold finish. Creates stunning light patterns and adds luxury to any room.",
    price: 5500000,
    monthlyPrice: 0,
    likeCount: 45,
    commentCount: 8,
    saveCount: 22,
    storeId: "store_2",
    tier: "goldenInstagramTagged",
    media: {
      mainImage: "https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?w=512&h=512&fit=crop",
      imageCarousel: [],
      is3DModel: false,
    },
  },
  {
    id: "product_4",
    name: "Silk Evening Gown",
    description: "Flowing silk gown in champagne gold. Perfect for formal events and special celebrations.",
    price: 3200000,
    monthlyPrice: 0,
    likeCount: 33,
    commentCount: 7,
    saveCount: 15,
    storeId: "store_2",
    tier: "stockProduct",
    media: {
      mainImage: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=512&h=512&fit=crop",
      imageCarousel: [],
      is3DModel: false,
    },
  },
  {
    id: "product_5",
    name: "Gold Jewelry Set",
    description: "Complete jewelry set including necklace, earrings, and bracelet. 24k gold plated with premium stones.",
    price: 4500000,
    monthlyPrice: 0,
    likeCount: 56,
    commentCount: 12,
    saveCount: 30,
    storeId: "store_1",
    tier: "goldenRegular",
    media: {
      mainImage: "https://images.unsplash.com/photo-1515562141589-67f0d569b6c9?w=512&h=512&fit=crop",
      imageCarousel: [],
      is3DModel: false,
    },
  },
  {
    id: "product_6",
    name: "Luxury Perfume",
    description: "Exclusive fragrance with notes of amber, vanilla, and gold leaf. Long-lasting and sophisticated scent.",
    price: 850000,
    monthlyPrice: 0,
    likeCount: 78,
    commentCount: 15,
    saveCount: 40,
    storeId: "store_3",
    tier: "stockProduct",
    media: {
      mainImage: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=512&h=512&fit=crop",
      imageCarousel: [],
      is3DModel: false,
    },
  },
  {
    id: "product_7",
    name: "Designer Sunglasses",
    description: "Premium sunglasses with gold-tone frames and UV protection. Fashion meets functionality.",
    price: 650000,
    monthlyPrice: 0,
    likeCount: 42,
    commentCount: 6,
    saveCount: 18,
    storeId: "store_3",
    tier: "stockProduct",
    media: {
      mainImage: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=512&h=512&fit=crop",
      imageCarousel: [],
      is3DModel: false,
    },
  },
  {
    id: "product_8",
    name: "Marble Coffee Table",
    description: "Modern coffee table with white marble top and gold metal base. Statement piece for living rooms.",
    price: 3800000,
    monthlyPrice: 0,
    likeCount: 29,
    commentCount: 4,
    saveCount: 11,
    storeId: "store_2",
    tier: "goldenRegular",
    media: {
      mainImage: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=512&h=512&fit=crop",
      imageCarousel: [],
      is3DModel: false,
    },
  },
]

export const mockStores: StoreProfile[] = [
  {
    owner: "store_1",
    name: "Golden Luxe Boutique",
    description: "Premium luxury products for the distinguished customer.",
    addressLink: "https://maps.google.com",
    assistantKnowledge: "We offer premium luxury goods.",
    mode: "golden",
    media: { storeImages: [] },
  },
  {
    owner: "store_2",
    name: "Elegance Home",
    description: "Beautiful home decor and fashion items.",
    addressLink: "https://maps.google.com",
    assistantKnowledge: "Home decor and fashion.",
    mode: "golden",
    media: { storeImages: [] },
  },
  {
    owner: "store_3",
    name: "Everyday Essentials",
    description: "Quality everyday products at great prices.",
    addressLink: "",
    assistantKnowledge: "",
    mode: "stock",
    media: { storeImages: [] },
  },
]

export const mockComments: Comment[] = [
  { id: "c1", content: "Juda chiroyli soat! Sifati ham a'lo darajada.", productId: "product_1", author: "user_1", timestamp: Date.now() - 86400000 },
  { id: "c2", content: "Narxi mos. Yetkazib berish tezligi ham yaxshi.", productId: "product_1", author: "user_2", timestamp: Date.now() - 43200000 },
  { id: "c3", content: "Bu sumka haqiqatan ham premium sifat!", productId: "product_2", author: "user_3", timestamp: Date.now() - 172800000 },
]

export const mockChatThreads: ChatThread[] = [
  {
    id: "thread_1",
    status: { type: "ongoing" },
    messages: [
      { id: "m1", content: "Salom! Bu soat haqida savol bermoqchiman.", sender: "user_1", timestamp: Date.now() - 3600000 },
      { id: "m2", content: "Salom! Qanday savolingiz bor?", sender: "store_1", timestamp: Date.now() - 3500000 },
    ],
    productId: "product_1",
    store: "store_1",
    buyer: "user_1",
    lastUpdate: Date.now() - 3500000,
  },
]
