export type Locale = "uz_Latn" | "uz_Cyrl" | "ru" | "en"

export const localeNames: Record<Locale, string> = {
  uz_Latn: "O'zbekcha (Lotin)",
  uz_Cyrl: "Ўзбекча (Кирилл)",
  ru: "Русский",
  en: "English",
}

const uz_Latn = {
  common: { loading: "Yuklanmoqda...", cancel: "Bekor qilish", save: "Saqlash", delete: "O'chirish", edit: "Tahrirlash", confirm: "Tasdiqlash", back: "Orqaga", close: "Yopish", search: "Qidirish", filter: "Filtr", sort: "Saralash", apply: "Qo'llash", reset: "Tiklash", saving: "Saqlanmoqda...", send: "Yuborish" },
  auth: { login: "Kirish", logout: "Chiqish", loggingIn: "Kirilmoqda...", loginRequired: "Iltimos, avval tizimga kiring", subtitle: "Mahsulotlarni kashf eting va do'konlar bilan bog'laning", profileSetupTitle: "Profil sozlash", profileSetupDescription: "Davom etish uchun ismingizni kiriting", continue: "Davom etish" },
  tabs: { products: "Mahsulotlar", chats: "Chatlar", saved: "Saqlangan", profile: "Profil", myStore: "Do'konim" },
  products: { title: "Mahsulotlar", searchPlaceholder: "Mahsulotlarni qidirish...", noProducts: "Mahsulotlar topilmadi", noResults: "Hech narsa topilmadi", addToCart: "Savatga qo'shish", viewDetails: "Batafsil", price: "Narx", description: "Tavsif", aiSearch: "AI Qidiruv", aiSearchPlaceholder: "AI yordamida mahsulotlarni qidiring...", send: "Yuborish", gallery: "Galereya", goldenProducts: "Golden mahsulotlar", stockProducts: "Stock mahsulotlar", allProducts: "Barcha mahsulotlar", comments: "Izohlar", noComments: "Hozircha izohlar yo'q", addComment: "Izoh qo'shish", commentPlaceholder: "Izohingizni yozing...", profile: "Profil", requestHumanSeller: "Sotuvchi bilan bog'lanish", requestHumanSellerMessage: "Sotuvchi bilan gaplashmoqchiman", endChat: "Chatni tugatish", messagePlaceholder: "Xabar yozing...", systemMessage: "Do'kon sotuvchisi chatni o'z zimmasiga oldi. Endi siz inson bilan gaplashyapsiz, AI emas.", chatPlaceholder: "Xabar yozing...", chatWindowEmpty: "AI yordamida mahsulotlarni qidiring...", selectImage: "Rasm tanlash" },
  chats: { title: "Chatlarim", noChats: "Hozircha chatlar yo'q", ended: "Tugagan", retentionNotice: "Tugagan chatlar 7 kundan keyin avtomatik o'chiriladi", loadingProduct: "Mahsulot yuklanmoqda...", productUnavailable: "Mahsulot mavjud emas", ongoing: "Davom etmoqda", takenOver: "Sotuvchi tomonidan boshqarilmoqda" },
  saved: { title: "Saqlangan", noSaved: "Saqlangan mahsulotlar yo'q", savedProducts: "Saqlangan mahsulotlar", recommendedProducts: "Tavsiya etilgan mahsulotlar" },
  store: { title: "Do'konim", becomeSellerTitle: "Sotuvchi bo'lish", becomeSellerDescription: "Do'koningizni oching va mahsulotlaringizni sotishni boshlang", becomeSeller: "Sotuvchi bo'lish", loginRequired: "Iltimos, avval tizimga kiring", storeCreatedSuccess: "Do'kon muvaffaqiyatli yaratildi", storeCreatedError: "Do'kon yaratishda xatolik", notifications: "Bildirishnomalar", messages: "Xabarlar", myProducts: "Mening mahsulotlarim", addProduct: "Mahsulot qo'shish", noProducts: "Hozircha mahsulotlar yo'q", stockLimitReached: "Stock do'konlar faqat 10 ta mahsulot qo'shishi mumkin", productName: "Mahsulot nomi", productNamePlaceholder: "Mahsulot nomini kiriting", productDescription: "Mahsulot tavsifi", productDescriptionPlaceholder: "Mahsulot tavsifini kiriting", productPrice: "Mahsulot narxi", productPricePlaceholder: "Narxni kiriting", productImages: "Mahsulot rasmlari", productVideo: "Mahsulot videosi", productAddedSuccess: "Mahsulot muvaffaqiyatli qo'shildi", productDeletedSuccess: "Mahsulot muvaffaqiyatli o'chirildi", storeInformationButton: "Do'kon ma'lumotlari", goldenAssistant: "Golden AI yordamchi", assistantKnowledge: "AI yordamchi bilimlar bazasi", assistantKnowledgePlaceholder: "Do'koningiz haqida ma'lumot kiriting...", upgradeToGoldenTitle: "Golden ga o'tish", upgradeToGoldenSubtitle: "Cheksiz mahsulotlar va AI yordamchi", upgradeButton: "Golden ga o'tish", name: "Do'kon nomi", namePlaceholder: "Do'kon nomini kiriting", description: "Do'kon tavsifi", descriptionPlaceholder: "Do'kon tavsifini kiriting", saveButton: "Saqlash", updating: "Yangilanmoqda...", goldenLabel: "Golden" },
  profile: { title: "Profil", displayName: "Ko'rsatiladigan ism", editDisplayName: "Ismni tahrirlash", enterName: "Ismingizni kiriting", nameSaved: "Ism saqlandi", language: "Til", selectLanguage: "Tilni tanlang", appearance: "Ko'rinish", darkMode: "Qorong'u rejim", legalRules: "Huquqiy qoidalar", viewLegalRules: "Huquqiy qoidalarni ko'rish", myActivity: "Mening faoliyatim", myLikes: "Mening yoqtirishlarim", myComments: "Mening izohlarim", mySubscriptions: "Mening obunalarim", likes: "Yoqtirishlar", comments: "Izohlar", subscriptions: "Obunalar", noLikes: "Hozircha yoqtirishlar yo'q", noComments: "Hozircha izohlar yo'q", noSubscriptions: "Hozircha obunalar yo'q", itemsCount: "{{count}} ta element" },
  assistant: { title: "AI yordamchi", greeting: "Salom! Men sizga mahsulotlar haqida ma'lumot berishda yordam bera olaman.", placeholder: "Savolingizni yozing...", productPlaceholder: "Mahsulot haqida savol bering...", talkToOwner: "Egasi bilan gaplashish", genericError: "Xatolik yuz berdi" },
  legal: { heading: "AlphaSpace - Qoidalar va Shartlar", pleaseRead: "Iltimos, davom etishdan oldin diqqat bilan o'qing", checkboxLabel: "Men barcha qoidalar va shartlarni o'qidim va to'liq roziman", confirmButton: "Tasdiqlash va davom etish", disclaimerText: "AlphaSpace platformasi foydalanuvchilar o'rtasida mahsulot va xizmatlar almashuvini osonlashtirish uchun yaratilgan." },
  notifications: { newChatStarted: "Yangi chat boshlandi", humanSellerRequested: "Mijoz sotuvchi bilan gaplashishni so'radi", markAsRead: "O'qilgan deb belgilash", noNotifications: "Bildirishnomalar yo'q" },
}

const en = {
  common: { loading: "Loading...", cancel: "Cancel", save: "Save", delete: "Delete", edit: "Edit", confirm: "Confirm", back: "Back", close: "Close", search: "Search", filter: "Filter", sort: "Sort", apply: "Apply", reset: "Reset", saving: "Saving...", send: "Send" },
  auth: { login: "Login", logout: "Logout", loggingIn: "Logging in...", loginRequired: "Please login first", subtitle: "Discover products and connect with stores", profileSetupTitle: "Profile Setup", profileSetupDescription: "Enter your name to continue", continue: "Continue" },
  tabs: { products: "Products", chats: "Chats", saved: "Saved", profile: "Profile", myStore: "My Store" },
  products: { title: "Products", searchPlaceholder: "Search products...", noProducts: "No products found", noResults: "Nothing found", addToCart: "Add to cart", viewDetails: "View details", price: "Price", description: "Description", aiSearch: "AI Search", aiSearchPlaceholder: "Search products with AI...", send: "Send", gallery: "Gallery", goldenProducts: "Golden products", stockProducts: "Stock products", allProducts: "All products", comments: "Comments", noComments: "No comments yet", addComment: "Add comment", commentPlaceholder: "Write your comment...", profile: "Profile", requestHumanSeller: "Contact seller", endChat: "End chat", messagePlaceholder: "Write a message...", chatWindowEmpty: "Search products with AI...", selectImage: "Select image" },
  chats: { title: "My Chats", noChats: "No chats yet", ended: "Ended", retentionNotice: "Ended chats are automatically deleted after 7 days", loadingProduct: "Loading product...", productUnavailable: "Product unavailable", ongoing: "Ongoing", takenOver: "Managed by seller" },
  saved: { title: "Saved", noSaved: "No saved items", savedProducts: "Saved products", recommendedProducts: "Recommended products" },
  store: { title: "My Store", becomeSellerTitle: "Become a Seller", becomeSellerDescription: "Open your store and start selling your products", becomeSeller: "Become a Seller", loginRequired: "Please login first", storeCreatedSuccess: "Store created successfully", storeCreatedError: "Error creating store", notifications: "Notifications", messages: "Messages", myProducts: "My Products", addProduct: "Add Product", noProducts: "No products yet", stockLimitReached: "Stock stores can only add 10 products", productName: "Product name", productNamePlaceholder: "Enter product name", productDescription: "Product description", productDescriptionPlaceholder: "Enter product description", productPrice: "Product price", productPricePlaceholder: "Enter price", productImages: "Product images", productVideo: "Product video", productAddedSuccess: "Product added successfully", productDeletedSuccess: "Product deleted successfully", storeInformationButton: "Store Information", goldenAssistant: "Golden AI Assistant", assistantKnowledge: "AI assistant knowledge base", assistantKnowledgePlaceholder: "Enter information about your store...", upgradeToGoldenTitle: "Upgrade to Golden", upgradeToGoldenSubtitle: "Unlimited products and AI assistant", upgradeButton: "Upgrade to Golden", name: "Store name", namePlaceholder: "Enter store name", description: "Store description", descriptionPlaceholder: "Enter store description", saveButton: "Save", updating: "Updating...", goldenLabel: "Golden" },
  profile: { title: "Profile", displayName: "Display name", editDisplayName: "Edit name", enterName: "Enter your name", nameSaved: "Name saved", language: "Language", selectLanguage: "Select language", appearance: "Appearance", darkMode: "Dark mode", legalRules: "Legal rules", viewLegalRules: "View legal rules", myActivity: "My Activity", myLikes: "My Likes", myComments: "My Comments", mySubscriptions: "My Subscriptions", likes: "Likes", comments: "Comments", subscriptions: "Subscriptions", noLikes: "No likes yet", noComments: "No comments yet", noSubscriptions: "No subscriptions yet", itemsCount: "{{count}} items" },
  assistant: { title: "AI Assistant", greeting: "Hello! I can help you with product information.", placeholder: "Write your question...", productPlaceholder: "Ask about a product...", talkToOwner: "Talk to owner", genericError: "An error occurred" },
  legal: { heading: "AlphaSpace - Rules and Terms", pleaseRead: "Please read carefully before continuing", checkboxLabel: "I have read and agree to all rules and terms", confirmButton: "Confirm and continue", disclaimerText: "The AlphaSpace platform is designed to facilitate the exchange of products and services between users." },
  notifications: { newChatStarted: "New chat started", humanSellerRequested: "Customer requested to talk to seller", markAsRead: "Mark as read", noNotifications: "No notifications" },
}

const ru = {
  common: { loading: "Загрузка...", cancel: "Отмена", save: "Сохранить", delete: "Удалить", edit: "Редактировать", confirm: "Подтвердить", back: "Назад", close: "Закрыть", search: "Поиск", filter: "Фильтр", sort: "Сортировка", apply: "Применить", reset: "Сбросить", saving: "Сохранение...", send: "Отправить" },
  auth: { login: "Войти", logout: "Выйти", loggingIn: "Вход...", loginRequired: "Пожалуйста, войдите в систему", subtitle: "Откройте для себя продукты и свяжитесь с магазинами", profileSetupTitle: "Настройка профиля", profileSetupDescription: "Введите ваше имя для продолжения", continue: "Продолжить" },
  tabs: { products: "Продукты", chats: "Чаты", saved: "Сохраненные", profile: "Профиль", myStore: "Мой магазин" },
  products: { title: "Продукты", searchPlaceholder: "Поиск продуктов...", noProducts: "Продукты не найдены", noResults: "Ничего не найдено", addToCart: "Добавить в корзину", viewDetails: "Подробнее", price: "Цена", description: "Описание", aiSearch: "AI Поиск", aiSearchPlaceholder: "Поиск продуктов с помощью AI...", send: "Отправить", gallery: "Галерея", goldenProducts: "Золотые продукты", stockProducts: "Stock продукты", allProducts: "Все продукты", comments: "Комментарии", noComments: "Пока нет комментариев", addComment: "Добавить комментарий", commentPlaceholder: "Напишите ваш комментарий...", profile: "Профиль", requestHumanSeller: "Связаться с продавцом", endChat: "Завершить чат", messagePlaceholder: "Напишите сообщение...", chatWindowEmpty: "Ищите продукты с помощью AI...", selectImage: "Выбрать изображение" },
  chats: { title: "Мои чаты", noChats: "Пока нет чатов", ended: "Завершен", retentionNotice: "Завершенные чаты автоматически удаляются через 7 дней", loadingProduct: "Загрузка продукта...", productUnavailable: "Продукт недоступен", ongoing: "Продолжается", takenOver: "Управляется продавцом" },
  saved: { title: "Сохраненные", noSaved: "Нет сохраненных", savedProducts: "Сохраненные продукты", recommendedProducts: "Рекомендуемые продукты" },
  store: { title: "Мой магазин", becomeSellerTitle: "Стать продавцом", becomeSellerDescription: "Откройте свой магазин и начните продавать свои продукты", becomeSeller: "Стать продавцом", loginRequired: "Пожалуйста, войдите в систему", storeCreatedSuccess: "Магазин успешно создан", storeCreatedError: "Ошибка создания магазина", notifications: "Уведомления", messages: "Сообщения", myProducts: "Мои продукты", addProduct: "Добавить продукт", noProducts: "Пока нет продуктов", stockLimitReached: "Stock магазины могут добавить только 10 продуктов", productName: "Название продукта", productNamePlaceholder: "Введите название продукта", productDescription: "Описание продукта", productDescriptionPlaceholder: "Введите описание продукта", productPrice: "Цена продукта", productPricePlaceholder: "Введите цену", productImages: "Изображения продукта", productVideo: "Видео продукта", productAddedSuccess: "Продукт успешно добавлен", productDeletedSuccess: "Продукт успешно удален", storeInformationButton: "Информация о магазине", goldenAssistant: "Золотой AI помощник", assistantKnowledge: "База знаний AI помощника", assistantKnowledgePlaceholder: "Введите информацию о вашем магазине...", upgradeToGoldenTitle: "Перейти на Golden", upgradeToGoldenSubtitle: "Неограниченные продукты и AI помощник", upgradeButton: "Перейти на Golden", name: "Название магазина", namePlaceholder: "Введите название магазина", description: "Описание магазина", descriptionPlaceholder: "Введите описание магазина", saveButton: "Сохранить", updating: "Обновление...", goldenLabel: "Golden" },
  profile: { title: "Профиль", displayName: "Отображаемое имя", editDisplayName: "Редактировать имя", enterName: "Введите ваше имя", nameSaved: "Имя сохранено", language: "Язык", selectLanguage: "Выберите язык", appearance: "Внешний вид", darkMode: "Темный режим", legalRules: "Правовые правила", viewLegalRules: "Просмотреть правовые правила", myActivity: "Моя активность", myLikes: "Мои лайки", myComments: "Мои комментарии", mySubscriptions: "Мои подписки", likes: "Лайки", comments: "Комментарии", subscriptions: "Подписки", noLikes: "Пока нет лайков", noComments: "Пока нет комментариев", noSubscriptions: "Пока нет подписок", itemsCount: "{{count}} элементов" },
  assistant: { title: "AI помощник", greeting: "Здравствуйте! Я могу помочь вам с информацией о продуктах.", placeholder: "Напишите ваш вопрос...", productPlaceholder: "Задайте вопрос о продукте...", talkToOwner: "Поговорить с владельцем", genericError: "Произошла ошибка" },
  legal: { heading: "Важное предупреждение", pleaseRead: "Пожалуйста, внимательно прочитайте перед продолжением", checkboxLabel: "Я прочитал условия и согласен", confirmButton: "Подтвердить и продолжить", disclaimerText: "Платформа AlphaSpace создана для облегчения обмена товарами и услугами между пользователями." },
  notifications: { newChatStarted: "Начат новый чат", humanSellerRequested: "Клиент попросил поговорить с продавцом", markAsRead: "Отметить как прочитанное", noNotifications: "Нет уведомлений" },
}

const uz_Cyrl = {
  common: { loading: "Юкланмоқда...", cancel: "Бекор қилиш", save: "Сақлаш", delete: "Ўчириш", edit: "Таҳрирлаш", confirm: "Тасдиқлаш", back: "Орқага", close: "Ёпиш", search: "Қидириш", filter: "Филтр", sort: "Саралаш", apply: "Қўллаш", reset: "Тиклаш", saving: "Сақланмоқда...", send: "Юбориш" },
  auth: { login: "Кириш", logout: "Чиқиш", loggingIn: "Кирилмоқда...", loginRequired: "Илтимос, аввал тизимга киринг", subtitle: "Маҳсулотларни кашф етинг ва дўконлар билан боғланинг", profileSetupTitle: "Профил созлаш", profileSetupDescription: "Давом етиш учун исмингизни киритинг", continue: "Давом етиш" },
  tabs: { products: "Маҳсулотлар", chats: "Чатлар", saved: "Сақланган", profile: "Профил", myStore: "Дўконим" },
  products: { title: "Маҳсулотлар", searchPlaceholder: "Маҳсулотларни қидириш...", noProducts: "Маҳсулотлар топилмади", noResults: "Ҳеч нарса топилмади", addToCart: "Саватга қўшиш", viewDetails: "Батафсил", price: "Нарх", description: "Тавсиф", aiSearch: "AI Қидирув", aiSearchPlaceholder: "AI ёрдамида маҳсулотларни қидиринг...", send: "Юбориш", gallery: "Галерея", goldenProducts: "Golden маҳсулотлар", stockProducts: "Stock маҳсулотлар", allProducts: "Барча маҳсулотлар", comments: "Изоҳлар", noComments: "Ҳозирча изоҳлар йўқ", addComment: "Изоҳ қўшиш", commentPlaceholder: "Изоҳингизни ёзинг...", profile: "Профил", requestHumanSeller: "Сотувчи билан боғланиш", endChat: "Чатни тугатиш", messagePlaceholder: "Хабар ёзинг...", chatWindowEmpty: "AI ёрдамида маҳсулотларни қидиринг...", selectImage: "Расм танлаш" },
  chats: { title: "Чатларим", noChats: "Ҳозирча чатлар йўқ", ended: "Тугаган", retentionNotice: "Тугаган чатлар 7 кундан кейин автоматик ўчирилади", loadingProduct: "Маҳсулот юкланмоқда...", productUnavailable: "Маҳсулот мавжуд емас", ongoing: "Давом етмоқда", takenOver: "Сотувчи томонидан бошқарилмоқда" },
  saved: { title: "Сақланган", noSaved: "Сақланган маҳсулотлар йўқ", savedProducts: "Сақланган маҳсулотлар", recommendedProducts: "Тавсия етилган маҳсулотлар" },
  store: { title: "Дўконим", becomeSellerTitle: "Сотувчи бўлиш", becomeSellerDescription: "Дўконингизни очинг ва маҳсулотларингизни сотишни бошланг", becomeSeller: "Сотувчи бўлиш", loginRequired: "Илтимос, аввал тизимга киринг", storeCreatedSuccess: "Дўкон муваффақиятли яратилди", storeCreatedError: "Дўкон яратишда хатолик", notifications: "Билдиришномалар", messages: "Хабарлар", myProducts: "Менинг маҳсулотларим", addProduct: "Маҳсулот қўшиш", noProducts: "Ҳозирча маҳсулотлар йўқ", stockLimitReached: "Stock дўконлар фақат 10 та маҳсулот қўшиши мумкин", productName: "Маҳсулот номи", productNamePlaceholder: "Маҳсулот номини киритинг", productDescription: "Маҳсулот тавсифи", productDescriptionPlaceholder: "Маҳсулот тавсифини киритинг", productPrice: "Маҳсулот нархи", productPricePlaceholder: "Нархни киритинг", productImages: "Маҳсулот расмлари", productVideo: "Маҳсулот видеоси", productAddedSuccess: "Маҳсулот муваффақиятли қўшилди", productDeletedSuccess: "Маҳсулот муваффақиятли ўчирилди", storeInformationButton: "Дўкон маълумотлари", goldenAssistant: "Golden AI ёрдамчи", assistantKnowledge: "AI ёрдамчи билимлар базаси", assistantKnowledgePlaceholder: "Дўконингиз ҳақида маълумот киритинг...", upgradeToGoldenTitle: "Golden га ўтиш", upgradeToGoldenSubtitle: "Чексиз маҳсулотлар ва AI ёрдамчи", upgradeButton: "Golden га ўтиш", name: "Дўкон номи", namePlaceholder: "Дўкон номини киритинг", description: "Дўкон тавсифи", descriptionPlaceholder: "Дўкон тавсифини киритинг", saveButton: "Сақлаш", updating: "Янгиланмоқда...", goldenLabel: "Golden" },
  profile: { title: "Профил", displayName: "Кўрсатиладиган исм", editDisplayName: "Исмни таҳрирлаш", enterName: "Исмингизни киритинг", nameSaved: "Исм сақланди", language: "Тил", selectLanguage: "Тилни танланг", appearance: "Кўриниш", darkMode: "Қоронғу режим", legalRules: "Қонуний қоидалар", viewLegalRules: "Қонуний қоидаларни кўриш", myActivity: "Менинг фаолиятим", myLikes: "Менинг ёқтиришларим", myComments: "Менинг шарҳларим", mySubscriptions: "Менинг обуналарим", likes: "Ёқтиришлар", comments: "Шарҳлар", subscriptions: "Обуналар", noLikes: "Ҳозирча ёқтиришлар йўқ", noComments: "Ҳозирча шарҳлар йўқ", noSubscriptions: "Ҳозирча обуналар йўқ", itemsCount: "{{count}} та элемент" },
  assistant: { title: "AI ёрдамчиси", greeting: "Салом! Мен сизга маҳсулотлар ҳақида маълумот беришда ёрдам бера оламан.", placeholder: "Саволингизни ёзинг...", productPlaceholder: "Маҳсулот ҳақида савол беринг...", talkToOwner: "Егаси билан гаплашиш", genericError: "Хатолик юз берди" },
  legal: { heading: "Муҳим огоҳлантириш", pleaseRead: "Илтимос, давом етишдан олдин диққат билан ўқинг", checkboxLabel: "Мен шартларни ўқидим ва розиман", confirmButton: "Тасдиқлаш ва давом етиш", disclaimerText: "AlphaSpace платформаси фойдаланувчилар ўртасида маҳсулот ва хизматлар алмашинувини осонлаштириш учун яратилган." },
  notifications: { newChatStarted: "Янги чат бошланди", humanSellerRequested: "Мижоз сотувчи билан гаплашишни сўради", markAsRead: "Ўқилган деб белгилаш", noNotifications: "Билдиришномалар йўқ" },
}

export const translations = { uz_Latn, uz_Cyrl, ru, en } as const
